### PR TITLE
Project 2 - Lisa

### PR DESCRIPTION
**Pull request by L-Lisa**
I joined the class late so have been short of time, tried to focus more on the technical flexbox practice than the design. I've been working with grids before so tried to combine those too, not sure what best practice is. Happy for any feedback. 
Finally, I had problems setting up the VS-Github-Netlify connection, any feedback on that would be useful too!
Thank you :)

### CODE REVIEW

**Comment by ericaglimsholt** [comment]
Hi! Can you add the Netlify link to your PR or Readme? :)

**Comment by L-Lisa** [comment]
Added :)

**Comment by L-Lisa** [comment]
Added the meta :)

**Comment by L-Lisa** [comment]
Thank you:)

**Pull request closed without merging**
