### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by lunek1**

### CODE REVIEW

**Comment by AntonellaMorittu** [comment]
Hi Cornelia, please provide us with the link to your deployed website, thank you :)

**Comment by lunek1** [comment]
Hi! 👋
I thought I did this when I handed in the projejct. If it somehow doesn't work could you please give me some instructions on how to do it. I've never used GitHub before this Boot Camp and I'm struggling a bit. 😅

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by AntonellaMorittu** [comment]
Hi Cornelia, in the material you will find the instructions on how to deploy your application with Netlify, it was part of the requirements. Check carefully and you will find the tutorial on how to do it, then you can share the link for reviews. Thank you :)

**Review by AntonellaMorittu — APPROVED** [review]
Hi Cornelia, well done for completing your first project! Your website looks very neat and with a well curated UI, I love the choice of colours and design - also I love Iceland 😍 You fulfilled the requirements and made a responsive app with grids and flexboxes, yay! 
Some improvements I can suggest are:
- use a formatter for css, it will take care of the spacing and indentations 
- move all images inside the assets folder, so the repo will be tidy and well organised

Keep up the good work! 👏

**Pull request closed without merging**
