### PR TITLE
Yifan Wang/News-site-for-pre-course

### PR DESCRIPTION
**Pull request by Yifan-858**

### CODE REVIEW

**Review by AntonellaMorittu — CHANGES_REQUESTED** [review]
Hi Yifan, good job completing your first assignment! It looks great! Please make sure that on tablets the number of columns displayed is 2 (tablets with bigger screens go up to max-width: 1024px). Update your repository to pass the assignment, thank you 💪

**Comment by Yifan-858** [comment]
Thank you! I just updated my repo. But I'm not sure how to mark the requested changes as "resolved".

**Review by AntonellaMorittu — CHANGES_REQUESTED** [review]
Hi Yifan, there is still no 2 columns applied to all tablet sizes. Is the link to the deployed version the same? Please refactor your code and follow the examples you can find on [Notion material](https://www.notion.so/technigo/Pre-Course-Tools-HTML-CSS-Flexbox-Grid-0ed0bd0101db40a2b36e61836a45c5d5). Thank you for reviewing your code :)

**Comment by Yifan-858** [comment]
Hey Antonella, I've updated the media queries for tablets as "@media only screen and (min-width: 481px) and (max-width: 1024px)" in the CSS file and pushed it to my repo. However, it seems that Netlify hasn't updated the site. I will try to deploy it again to see if that can solve the problem!

**Comment by Yifan-858** [comment]
I just deployed the site again in Netlify. It seems to be working now.

**Review by AntonellaMorittu — APPROVED** [review]

**Pull request closed without merging**
