### PR TITLE
Vinify

### PR DESCRIPTION
**Pull request by smily342**
Here is my first pull.

Greetings from switzerland

### CODE REVIEW

**Review by JennieDalgren — COMMENTED** [review]
The netlify link does not work

**Comment by smily342** [comment]
This is odd, I tested it before the submit. 

My apologies,  here is the link again
: https://66cb77f604cb7054838ffe7e--viny-fy.netlify.app/

**Review by JennieDalgren — CHANGES_REQUESTED** [review]
Your logo seems to be broken, check the path:
`Logo de Vinify`
This points to your local file on you computer but it needs to use the relative path for the project since your deployed version has no contact with your computer.

[Read more here](https://www.w3schools.com/html/html_filepaths.asp)

Other than that, good job with the project! 🎊

**Comment by smily342** [comment]
https://github.com/Technigo/project-news-site/pull/540
https://illustrious-macaron-4d543a.netlify.app/

Sorry my update can be see here

**Comment by smily342** [comment]
https://illustrious-macaron-4d543a.netlify.app/
https://github.com/Technigo/project-news-site/pull/540

**Pull request closed without merging**
