### PR TITLE
BloomNews_bmm 

### PR DESCRIPTION
**Pull request by Maria-Manuela**
Creating pull request

### CODE REVIEW

**Comment by AntonellaMorittu** [comment]
Hi Maria-Manuela, please link your deployed project so that we can review your work, thanks :)

**Comment by Maria-Manuela** [comment]
> Hi Maria-Manuela, please link your deployed project so that we can review your work, thanks :)

Hi Antonella, I am not sure exactly what or where to do that. I´ll try to submit it again and add my link. hopefully, it will work.

**Comment by Maria-Manuela** [comment]
I hope this will help:
https://ecobloomnews.netlify.app/

**Review by AntonellaMorittu — APPROVED** [review]
Well done with the pre-course Maria-Manuela! Your project meets the requirements and looks well organised and cute. I recommend to refactor the code, moving all the images inside the assets folder. Keep up the good work! 👏

**Pull request closed without merging**
