### PR TITLE
Lorenzo Dastoli project news site

### PR DESCRIPTION
**Pull request by Looziolooz**

### CODE REVIEW

**Comment by AntonellaMorittu** [comment]
Hi Lorenzo, please provide a link to your deployed version, the previous one you gave us it's not working anymore. Thank you :)

**Comment by Looziolooz** [comment]
Hi Antonella Hi Antonella, I apologize for the delay and for the various issues related to the project. Here is the link: https://main--ladolcevitamagazine.netlify.app/ Unfortunately, I encountered problems with the last step concerning Vite+React. Tomorrow, I will try to solve this problem as well. Thank you.

**Review by AntonellaMorittu — CHANGES_REQUESTED** [review]
Hi Lorenzo, great job completing your first project! 👏Your site looks neat and has a good layout. I will need you to apply some slight changes to meet the requirements:

- you were asked to use both flexboxes and grids. Although it looks perfectly fine as it is, you only used `display: flex`but the exercise implied for you to use both
- make sure not to exclude the screens in between 668px - 678px when you take care of the responsiveness

Also as a general tip, all the images should go into the assets folder, that's why we put it there for you :) This will make the structure of your repository tidy and organised.

 Please review these changes to get the pull request approved, almost there! 💪

**Comment by AntonellaMorittu** [comment]
Hi Lorenzo, sorry to hear you experienced some issues. The Netlify deployment info is valid for the whole course, that's why you have a tutorial on how to deploy with React, but that was not meant for you to follow right now. There is another one first that says "_Deploying a Simple Vanilla JS Website_" and that was the only one you should have focused on. Anyhow, now you made it 🤝 😄

**Comment by Looziolooz** [comment]
Hello Antonella, thank you for the comment and advice. I made the requested changes (I hope they are okay). I saved everything in the main branch. Let me know if I need to make any other changes. I placed all the photos outside the folder because Netlify wasn't loading the latest changes for me, I don't know why. Thanks again and have a good day.

**Comment by AntonellaMorittu** [comment]
Ciao Lorenzo! Great ⭐ I see your changes on the `main` branch, but since your Pull Request is open against your `master` branch you need to update that! I can approve your PR then, so just clean your code, delete the second branch and only keep one with the correct code. I also saw the structure in your `main` branch is quite messy, you want to keep all of your code in the `code` folder, like we had it prepared for you, and don't keep files unused laying around (I saw an `App.jsx` ???). If you have doubts, check the original repo you forked. Thank you and get well soon 🙌

**Pull request closed without merging**
